image: node:14

stages:
    - init
    - build
    - package

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - node_modules/

init:
    stage: init
    script:
        - npm config set registry "https://registry.npm.taobao.org"
        - npm config delete @xdtech:registry
        - yarn config set registry "https://registry.yarnpkg.com"
        - yarn config delete @xdtech:registry
        - yarn
    tags:
        - evergarden

build:staging:
    stage: build
    image: node:14
    script:
        - npm run tsc
    artifacts:
        name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_staging"
        paths:
        - ./
        expire_in: 1 day
    variables:
    only:
        - main
    tags:
        - evergarden

build:prod:
    stage: build
    image: node:14
    script:
        - npm run tsc
    artifacts:
        name: "${CI_BUILD_NAME}_${CI_COMMIT_TAG}"
        paths:
        - ./
        expire_in: 1 day
    variables:
    only:
        - tags
    tags:
        - evergarden

build:international:
    stage: build
    image: node:14
    script:
        - npm run tsc
    artifacts:
        name: "${CI_BUILD_NAME}_${CI_COMMIT_TAG}"
        paths:
        - ./
        expire_in: 1 day
    variables:
    only:
        - international
    tags:
        - evergarden

package:staging:
    stage: package
    image: docker:19.03.1
    script:
        - docker login -u $HARBOR_USERNAME -p $HARBOR_PWD registry.ugli.fans
        - docker build -t registry.ugli.fans/evergarden:staging-$CI_COMMIT_SHORT_SHA . --build-arg NPM_SCRIPT=start
        - docker push registry.ugli.fans/evergarden:staging-$CI_COMMIT_SHORT_SHA
        - docker rmi registry.ugli.fans/evergarden:staging-$CI_COMMIT_SHORT_SHA
    only:
        - main
    tags:
        - evergarden

package:prod:
    stage: package
    image: docker:19.03.1
    script:
        - docker login -u $HARBOR_USERNAME -p $HARBOR_PWD registry.ugli.fans
        - docker build -t registry.ugli.fans/evergarden:release-$CI_COMMIT_TAG . --build-arg NPM_SCRIPT=start
        - docker push registry.ugli.fans/evergarden:release-$CI_COMMIT_TAG
        - docker rmi registry.ugli.fans/evergarden:release-$CI_COMMIT_TAG
    only:
        - tags
    tags:
        - evergarden

package:international:
    stage: package
    image: docker:19.03.1
    script:
        - docker login -u $HARBOR_USERNAME -p $HARBOR_PWD registry.ugli.fans
        - docker build -t registry.ugli.fans/evergarden:release-$CI_COMMIT_SHORT_SHA . --build-arg NPM_SCRIPT=start-intl
        - docker push registry.ugli.fans/evergarden:release-$CI_COMMIT_SHORT_SHA
        - docker rmi registry.ugli.fans/evergarden:release-$CI_COMMIT_SHORT_SHA
    only:
        - international
    tags:
        - evergarden