apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ugli-nestjs-ns
  name: ugli-nestjs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ugli-nestjs
  template:
    metadata:
      labels:
        app: ugli-nestjs
    spec:
      imagePullSecrets:
        - name: localhost
      containers:
        - name: ugli-nestjs
          image: localhost:5000/ugli_nestjs:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: nestjs-secret-test