apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: ugli_nestjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ugli-nestjs
  template:
    metadata:
      labels:
        app: ugli-nestjs
    spec:
      containers:
      - name: ugli-nestjs
        image: registry.ugli.fans/ugli_nestjs:test
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: registry.ugli.fans