apiVersion: v1
kind: Service
metadata:
  namespace: ugli-nestjs-ns
  name: ugli-nestjs-service
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 31368
  selector:
    app: ugli-nestjs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ugli-nestjs-ns
  name: ugli-nestjs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ugli-nestjs
  template:
    metadata:
      labels:
        app: ugli-nestjs
    spec:
      imagePullSecrets:
        - name: localhost
      containers:
        - name: ugli-nestjs
          image: localhost:5000/ugli_nestjs:v0.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: nestjs-secret-test