apiVersion: v1
kind: Service
metadata:
  namespace: ugli-nestjs-ns
  name: ugli-nestjs-service
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 31368
  selector:
    app: ugli-nestjs